package edu.valle.modules.store.service.impl;
import edu.valle.exception.ResourceNotFoundException; import edu.valle.modules.catalog.entity.*; import edu.valle.modules.catalog.repository.*; import edu.valle.modules.inventory.repository.InventoryRepository; import edu.valle.modules.store.dto.response.*; import edu.valle.modules.store.service.StoreService; import java.util.*; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service @RequiredArgsConstructor public class StoreServiceImpl implements StoreService {
 private final ProductRepository products; private final ProductVariantRepository variants; private final InventoryRepository inventories;
 @Transactional(readOnly=true) public List<StoreCategoryResponse> categories(){return products.findByActiveTrue().stream().map(Product::getCategory).filter(c->Boolean.TRUE.equals(c.getActive())).collect(java.util.stream.Collectors.toMap(Category::getId,c->c,(a,b)->a,LinkedHashMap::new)).values().stream().map(c->new StoreCategoryResponse(c.getId(),c.getName(),c.getDescription())).toList();}
 @Transactional(readOnly=true) public List<StoreProductResponse> products(Long categoryId){List<Product> list=categoryId==null?products.findByActiveTrue():products.findByActiveTrueAndCategoryId(categoryId);return list.stream().filter(p->Boolean.TRUE.equals(p.getCategory().getActive())).map(this::map).toList();}
 @Transactional(readOnly=true) public StoreProductResponse product(Long id){Product p=products.findById(id).filter(v->Boolean.TRUE.equals(v.getActive())).filter(v->Boolean.TRUE.equals(v.getCategory().getActive())).orElseThrow(()->new ResourceNotFoundException("Product",id));return map(p);}
 private StoreProductResponse map(Product p){List<StoreVariantResponse> visible=variants.findByProductIdAndActiveTrue(p.getId()).stream().filter(v->Boolean.TRUE.equals(v.getActive())).map(v->new StoreVariantResponse(v.getId(),v.getSize(),v.getColor(),v.getSku(),inventories.findByProductVariantId(v.getId()).map(i->i.getCurrentStock()).orElse(0))).toList();return new StoreProductResponse(p.getId(),p.getName(),p.getDescription(),p.getSalePrice(),p.getCategory().getId(),p.getCategory().getName(),visible);}
}
