package edu.valle.modules.cart.service.impl;
import edu.valle.common.enums.UserRole; import edu.valle.exception.*; import edu.valle.modules.cart.dto.request.CartItemRequest; import edu.valle.modules.cart.dto.response.CartResponse; import edu.valle.modules.cart.entity.*; import edu.valle.modules.cart.mapper.CartMapper; import edu.valle.modules.cart.repository.*; import edu.valle.modules.cart.service.CartService; import edu.valle.modules.catalog.entity.ProductVariant; import edu.valle.modules.catalog.repository.ProductVariantRepository; import edu.valle.modules.inventory.entity.Inventory; import edu.valle.modules.inventory.repository.InventoryRepository; import edu.valle.modules.users.entity.User; import edu.valle.modules.users.repository.UserRepository; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service @RequiredArgsConstructor public class CartServiceImpl implements CartService {
 private final CartRepository carts; private final CartItemRepository items; private final ProductVariantRepository variants; private final InventoryRepository inventories; private final UserRepository users; private final CartMapper mapper;
 @Transactional public CartResponse get(String username){return mapper.toResponse(cart(username));}
 @Transactional public CartResponse add(String username,CartItemRequest r){Cart cart=cart(username);ProductVariant v=validVariant(r.productVariantId(),r.quantity());CartItem item=items.findByCartIdAndProductVariantId(cart.getId(),v.getId()).orElse(null);if(item==null){item=new CartItem();item.setProductVariant(v);item.setQuantity(r.quantity());cart.addItem(item);}else{int quantity=item.getQuantity()+r.quantity();validateStock(v,quantity);item.setQuantity(quantity);}return mapper.toResponse(carts.save(cart));}
 @Transactional public CartResponse update(String username,Long itemId,CartItemRequest r){CartItem item=items.findByIdAndCartCustomerUsername(itemId,username).orElseThrow(()->new ResourceNotFoundException("CartItem",itemId));ProductVariant v=validVariant(r.productVariantId(),r.quantity());if(!item.getProductVariant().getId().equals(v.getId())&&items.findByCartIdAndProductVariantId(item.getCart().getId(),v.getId()).isPresent())throw new BusinessException("Product variant already exists in cart");item.setProductVariant(v);item.setQuantity(r.quantity());items.save(item);return mapper.toResponse(item.getCart());}
 @Transactional public void remove(String username,Long itemId){CartItem item=items.findByIdAndCartCustomerUsername(itemId,username).orElseThrow(()->new ResourceNotFoundException("CartItem",itemId));Cart cart=item.getCart();cart.removeItem(item);carts.save(cart);}
 @Transactional public void clear(String username){Cart cart=cart(username);cart.clear();carts.save(cart);}
 private Cart cart(String username){return carts.findByCustomerUsername(username).orElseGet(()->{Cart c=new Cart();c.setCustomer(customer(username));return carts.save(c);});}
 private User customer(String username){User u=users.findByUsername(username).orElseThrow(()->new ResourceNotFoundException("User not found"));if(Boolean.FALSE.equals(u.getActive())||u.getRole()!=UserRole.CUSTOMER)throw new BusinessException("Active CUSTOMER role is required");return u;}
 private ProductVariant validVariant(Long id,int quantity){ProductVariant v=variants.findById(id).orElseThrow(()->new ResourceNotFoundException("ProductVariant",id));if(Boolean.FALSE.equals(v.getActive()))throw new BusinessException("Product variant is inactive");if(Boolean.FALSE.equals(v.getProduct().getActive()))throw new BusinessException("Product is inactive");validateStock(v,quantity);return v;}
 private void validateStock(ProductVariant v,int quantity){Inventory i=inventories.findByProductVariantId(v.getId()).orElseThrow(()->new ResourceNotFoundException("Inventory not found for product variant id: "+v.getId()));if(quantity>i.getCurrentStock())throw new BusinessException("Insufficient stock for product variant: "+v.getSku());}
}
