package edu.valle.modules.catalog.service.impl;
import static org.junit.jupiter.api.Assertions.*; import static org.mockito.Mockito.*;
import edu.valle.exception.BusinessException; import edu.valle.modules.catalog.dto.request.ProductVariantRequest; import edu.valle.modules.catalog.entity.*; import edu.valle.modules.catalog.mapper.ProductVariantMapper; import edu.valle.modules.catalog.repository.*; import edu.valle.modules.inventory.entity.Inventory; import edu.valle.modules.inventory.repository.InventoryRepository; import java.util.*; import org.junit.jupiter.api.*; import org.junit.jupiter.api.extension.ExtendWith; import org.mockito.*; import org.mockito.junit.jupiter.MockitoExtension;
@ExtendWith(MockitoExtension.class) class ProductVariantServiceImplTest {
 @Mock ProductVariantRepository variants; @Mock ProductRepository products; @Mock InventoryRepository inventories; @Mock ProductVariantMapper mapper; ProductVariantServiceImpl service; Product product;
 @BeforeEach void setup(){service=new ProductVariantServiceImpl(variants,products,inventories,mapper);product=new Product();product.setId(1L);product.setActive(true);}
 @Test void createsVariantAndItsInventory(){ProductVariantRequest r=new ProductVariantRequest(1L," m "," negro ","CAM-M-NEG",null);ProductVariant v=new ProductVariant();v.setId(2L);when(products.findById(1L)).thenReturn(Optional.of(product));when(variants.findByProductId(1L)).thenReturn(List.of());when(variants.findBySkuIgnoreCase("CAM-M-NEG")).thenReturn(Optional.empty());when(mapper.toEntity(r)).thenReturn(v);when(variants.save(v)).thenReturn(v);service.create(r);assertEquals("M",v.getSize());assertEquals("NEGRO",v.getColor());ArgumentCaptor<Inventory> c=ArgumentCaptor.forClass(Inventory.class);verify(inventories).save(c.capture());assertSame(v,c.getValue().getProductVariant());}
 @Test void rejectsDuplicateSku(){ProductVariantRequest r=new ProductVariantRequest(1L,"M","Negro","SKU-1",true);ProductVariant existing=new ProductVariant();existing.setId(8L);when(products.findById(1L)).thenReturn(Optional.of(product));when(variants.findBySkuIgnoreCase("SKU-1")).thenReturn(Optional.of(existing));assertThrows(BusinessException.class,()->service.create(r));}
 @Test void rejectsEquivalentSizeAndColor(){ProductVariantRequest r=new ProductVariantRequest(1L," m ","negro","SKU-2",true);ProductVariant existing=new ProductVariant();existing.setId(8L);existing.setSize("M");existing.setColor(" NEGRO ");when(products.findById(1L)).thenReturn(Optional.of(product));when(variants.findBySkuIgnoreCase("SKU-2")).thenReturn(Optional.empty());when(variants.findByProductId(1L)).thenReturn(List.of(existing));assertThrows(BusinessException.class,()->service.create(r));}
}
