-- Esquema de referencia para la fase 1 de tienda de ropa.
-- Base de desarrollo: tienda_ropa. No crea, elimina ni modifica bases de datos.

CREATE TABLE IF NOT EXISTS users (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,full_name VARCHAR(120) NOT NULL,email VARCHAR(120) NOT NULL UNIQUE,username VARCHAR(60) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL,role VARCHAR(30) NOT NULL CHECK(role IN('ADMIN','SELLER','CUSTOMER')),active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMP NOT NULL,updated_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS categories (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name VARCHAR(100) NOT NULL UNIQUE,description VARCHAR(500),active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMP NOT NULL,updated_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS products (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name VARCHAR(150) NOT NULL,description VARCHAR(700),sale_price NUMERIC(12,2) NOT NULL,cost_price NUMERIC(12,2) NOT NULL,active BOOLEAN NOT NULL DEFAULT TRUE,category_id BIGINT NOT NULL REFERENCES categories(id),created_at TIMESTAMP NOT NULL,updated_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS product_variants (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,product_id BIGINT NOT NULL REFERENCES products(id),size VARCHAR(30) NOT NULL,color VARCHAR(50) NOT NULL,sku VARCHAR(80) NOT NULL UNIQUE,active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMP NOT NULL,updated_at TIMESTAMP NOT NULL,CONSTRAINT uk_product_variant_product_size_color UNIQUE(product_id,size,color));
CREATE TABLE IF NOT EXISTS inventories (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,product_variant_id BIGINT NOT NULL UNIQUE REFERENCES product_variants(id),current_stock INTEGER NOT NULL DEFAULT 0,min_stock INTEGER NOT NULL DEFAULT 0,max_stock INTEGER,created_at TIMESTAMP NOT NULL,updated_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS stock_movements (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,product_variant_id BIGINT NOT NULL REFERENCES product_variants(id),user_id BIGINT NOT NULL REFERENCES users(id),movement_type VARCHAR(30) NOT NULL,quantity INTEGER NOT NULL,previous_stock INTEGER NOT NULL,new_stock INTEGER NOT NULL,reason VARCHAR(500),created_at TIMESTAMP NOT NULL,updated_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS sales (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,sale_number VARCHAR(50) NOT NULL UNIQUE,user_id BIGINT NOT NULL REFERENCES users(id),sale_date TIMESTAMP NOT NULL,subtotal NUMERIC(12,2) NOT NULL,tax NUMERIC(12,2) NOT NULL,discount NUMERIC(12,2) NOT NULL,total NUMERIC(12,2) NOT NULL,status VARCHAR(30) NOT NULL CHECK(status IN('PENDING','PAID','PREPARING','DELIVERED','CANCELLED')),created_at TIMESTAMP NOT NULL,updated_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS sale_items (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,sale_id BIGINT NOT NULL REFERENCES sales(id),product_variant_id BIGINT NOT NULL REFERENCES product_variants(id),quantity INTEGER NOT NULL,unit_price NUMERIC(12,2) NOT NULL,subtotal NUMERIC(12,2) NOT NULL,created_at TIMESTAMP NOT NULL,updated_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS payments (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,sale_id BIGINT NOT NULL REFERENCES sales(id),payment_method VARCHAR(30) NOT NULL,amount NUMERIC(12,2) NOT NULL,paid_at TIMESTAMP NOT NULL,created_at TIMESTAMP NOT NULL,updated_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS carts (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,customer_id BIGINT NOT NULL UNIQUE REFERENCES users(id),created_at TIMESTAMP NOT NULL,updated_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS cart_items (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,cart_id BIGINT NOT NULL REFERENCES carts(id),product_variant_id BIGINT NOT NULL REFERENCES product_variants(id),quantity INTEGER NOT NULL CHECK(quantity>0),created_at TIMESTAMP NOT NULL,updated_at TIMESTAMP NOT NULL,CONSTRAINT uk_cart_item_variant UNIQUE(cart_id,product_variant_id));

CREATE INDEX IF NOT EXISTS idx_products_category_id ON products(category_id);
CREATE INDEX IF NOT EXISTS idx_product_variants_product_id ON product_variants(product_id);
CREATE INDEX IF NOT EXISTS idx_stock_movements_variant_id ON stock_movements(product_variant_id);
CREATE INDEX IF NOT EXISTS idx_stock_movements_user_id ON stock_movements(user_id);
CREATE INDEX IF NOT EXISTS idx_sales_user_id ON sales(user_id);
CREATE INDEX IF NOT EXISTS idx_sale_items_sale_id ON sale_items(sale_id);
CREATE INDEX IF NOT EXISTS idx_sale_items_variant_id ON sale_items(product_variant_id);
CREATE INDEX IF NOT EXISTS idx_payments_sale_id ON payments(sale_id);
CREATE INDEX IF NOT EXISTS idx_carts_customer_id ON carts(customer_id);
CREATE INDEX IF NOT EXISTS idx_cart_items_cart_id ON cart_items(cart_id);
CREATE INDEX IF NOT EXISTS idx_cart_items_variant_id ON cart_items(product_variant_id);
