-- Script PostgreSQL para el proyecto DeberMVP
-- Base de datos configurada en application.properties: jdbc:postgresql://localhost:5432/Tienda

-- Primero crea la base de datos si no existe:
-- CREATE DATABASE "Tienda";
--
-- Luego conectate a la base "Tienda" y ejecuta el resto del script.
-- En psql puedes usar: \c "Tienda"

DROP TABLE IF EXISTS ventas CASCADE;
DROP TABLE IF EXISTS productos CASCADE;
DROP TABLE IF EXISTS categorias CASCADE;

CREATE TABLE categorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255),
    descripcion VARCHAR(255)
);

CREATE TABLE productos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255),
    descripcion VARCHAR(255),
    precio NUMERIC(38, 2),
    stock INTEGER,
    categoria_id BIGINT,
    CONSTRAINT fk_productos_categorias
        FOREIGN KEY (categoria_id)
        REFERENCES categorias (id)
);

CREATE TABLE ventas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha TIMESTAMP(6),
    cantidad INTEGER,
    total NUMERIC(38, 2),
    producto_id BIGINT,
    CONSTRAINT fk_ventas_productos
        FOREIGN KEY (producto_id)
        REFERENCES productos (id)
);

CREATE INDEX idx_productos_categoria_id ON productos (categoria_id);
CREATE INDEX idx_ventas_producto_id ON ventas (producto_id);

-- Datos de prueba opcionales
INSERT INTO categorias (nombre, descripcion) VALUES
('Bebidas', 'Productos liquidos para consumo'),
('Snacks', 'Productos de consumo rapido');

INSERT INTO productos (nombre, descripcion, precio, stock, categoria_id) VALUES
('Agua mineral', 'Botella de agua 500ml', 0.75, 100, 1),
('Papas fritas', 'Funda pequena de papas', 1.25, 50, 2);

-- Ejemplo de venta registrada directamente en SQL.
-- En tu aplicacion, la venta normalmente se crea desde /api/ventas,
-- donde el servicio calcula el total, asigna la fecha y descuenta el stock.
INSERT INTO ventas (fecha, cantidad, total, producto_id) VALUES
(NOW(), 2, 1.50, 1);

UPDATE productos
SET stock = stock - 2
WHERE id = 1;
