-- Esquema independiente del proveedor SOAP.
-- Ejecutar conectado a supplier_db. No elimina bases ni tablas existentes.

CREATE TABLE IF NOT EXISTS supplier_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(150) NOT NULL,
    size VARCHAR(30) NOT NULL,
    color VARCHAR(50) NOT NULL,
    sku VARCHAR(80) NOT NULL UNIQUE,
    price NUMERIC(12, 2) NOT NULL CHECK (price >= 0),
    available_stock INTEGER NOT NULL DEFAULT 0 CHECK (available_stock >= 0),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_supplier_products_sku_lower
    ON supplier_products (LOWER(sku));

CREATE INDEX IF NOT EXISTS idx_supplier_products_active
    ON supplier_products (active);

-- Datos opcionales de ejemplo:
-- INSERT INTO supplier_products(product_name,size,color,sku,price,available_stock)
-- VALUES ('Camiseta básica','M','NEGRO','CAM-M-NEG',8.50,100);
