package edu.valle.modules.sales.service.impl;
import static org.junit.jupiter.api.Assertions.*; import static org.mockito.Mockito.*;
import edu.valle.common.enums.*; import edu.valle.exception.BusinessException; import edu.valle.modules.cart.entity.*; import edu.valle.modules.cart.repository.CartRepository; import edu.valle.modules.catalog.entity.*; import edu.valle.modules.catalog.repository.ProductVariantRepository; import edu.valle.modules.inventory.entity.Inventory; import edu.valle.modules.inventory.repository.*; import edu.valle.modules.payments.entity.Payment; import edu.valle.modules.payments.repository.PaymentRepository; import edu.valle.modules.sales.dto.request.*; import edu.valle.modules.sales.entity.*; import edu.valle.modules.sales.mapper.SaleMapper; import edu.valle.modules.sales.repository.SaleRepository; import edu.valle.modules.users.entity.User; import edu.valle.modules.users.repository.UserRepository; import java.math.BigDecimal; import java.util.*; import org.junit.jupiter.api.*; import org.junit.jupiter.api.extension.ExtendWith; import org.mockito.*; import org.mockito.junit.jupiter.MockitoExtension;
@ExtendWith(MockitoExtension.class) class SaleServiceImplTest {
 @Mock SaleRepository sales; @Mock ProductVariantRepository variants; @Mock InventoryRepository inventories; @Mock StockMovementRepository movements; @Mock PaymentRepository payments; @Mock UserRepository users; @Mock CartRepository carts; @Mock SaleMapper mapper; SaleServiceImpl service; User customer; ProductVariant variant; Inventory inventory;
 @BeforeEach void setup(){service=new SaleServiceImpl(sales,variants,inventories,movements,payments,users,carts,mapper);customer=new User();customer.setId(1L);customer.setUsername("ana");customer.setRole(UserRole.CUSTOMER);customer.setActive(true);Product p=new Product();p.setId(3L);p.setName("Camiseta");p.setSalePrice(new BigDecimal("20.00"));p.setActive(true);variant=new ProductVariant();variant.setId(7L);variant.setSku("CAM-M-N");variant.setActive(true);variant.setProduct(p);inventory=new Inventory();inventory.setProductVariant(variant);}
 private CreateSaleRequest request(int q){return new CreateSaleRequest(1L,BigDecimal.ZERO,BigDecimal.ZERO,PaymentMethod.CASH,null,List.of(new CreateSaleItemRequest(7L,q)));}
 private void stockMocks(){when(variants.findById(7L)).thenReturn(Optional.of(variant));when(inventories.findByProductVariantIdForUpdate(7L)).thenReturn(Optional.of(inventory));}
 private Cart cart(int q){Cart c=new Cart();c.setId(9L);c.setCustomer(customer);CartItem i=new CartItem();i.setId(11L);i.setProductVariant(variant);i.setQuantity(q);c.addItem(i);return c;}
 @Test void rejectsInsufficientStockWithoutCreatingSaleOrPayment(){inventory.setCurrentStock(1);when(users.findById(1L)).thenReturn(Optional.of(customer));stockMocks();assertThrows(BusinessException.class,()->service.create(request(2)));verify(sales,never()).save(any());verify(payments,never()).save(any());}
 @Test void administrativeSaleDeductsLockedInventory(){inventory.setCurrentStock(5);when(users.findById(1L)).thenReturn(Optional.of(customer));stockMocks();when(sales.save(any())).thenAnswer(i->i.getArgument(0));when(payments.save(any())).thenAnswer(i->i.getArgument(0));service.create(request(2));assertEquals(3,inventory.getCurrentStock());verify(movements).save(argThat(m->m.getProductVariant()==variant&&m.getQuantity()==2));}
 @Test void checkoutCalculatesTotalCreatesPaidSaleAndClearsCart(){inventory.setCurrentStock(5);Cart cart=cart(2);when(users.findByUsername("ana")).thenReturn(Optional.of(customer));when(carts.findByCustomerUsername("ana")).thenReturn(Optional.of(cart));stockMocks();when(sales.save(any())).thenAnswer(i->{Sale s=i.getArgument(0);s.setId(20L);return s;});when(payments.save(any())).thenAnswer(i->i.getArgument(0));service.checkout("ana",new CheckoutRequest(PaymentMethod.TRANSFER));ArgumentCaptor<Sale> sale=ArgumentCaptor.forClass(Sale.class);verify(sales).save(sale.capture());assertEquals(new BigDecimal("40.00"),sale.getValue().getTotal());assertEquals(SaleStatus.PAID,sale.getValue().getStatus());assertEquals(1,sale.getValue().getItems().size());verify(payments).save(argThat(p->p.getAmount().equals(new BigDecimal("40.00"))));assertEquals(3,inventory.getCurrentStock());assertTrue(cart.getItems().isEmpty());verify(carts).save(cart);}
 @Test void checkoutRejectsEmptyCartWithoutSideEffects(){Cart cart=cart(1);cart.clear();when(users.findByUsername("ana")).thenReturn(Optional.of(customer));when(carts.findByCustomerUsername("ana")).thenReturn(Optional.of(cart));assertThrows(BusinessException.class,()->service.checkout("ana",new CheckoutRequest(PaymentMethod.CASH)));verify(sales,never()).save(any());verify(inventories,never()).save(any());}
 @Test void customerOnlyReadsOwnOrders(){when(users.findByUsername("ana")).thenReturn(Optional.of(customer));when(sales.findByUserUsernameOrderBySaleDateDesc("ana")).thenReturn(List.of());service.findMyOrders("ana");verify(sales).findByUserUsernameOrderBySaleDateDesc("ana");verify(sales,never()).findAllByOrderBySaleDateDesc();}
 @Test void validStatusTransitionPaidToPreparing(){Sale sale=new Sale();sale.setId(30L);sale.setStatus(SaleStatus.PAID);when(sales.findByIdForUpdate(30L)).thenReturn(Optional.of(sale));when(sales.save(sale)).thenReturn(sale);when(payments.findBySaleIdOrderByPaidAtAsc(30L)).thenReturn(List.of());service.updateStatus(30L,new UpdateSaleStatusRequest(SaleStatus.PREPARING));assertEquals(SaleStatus.PREPARING,sale.getStatus());}
 @Test void rejectsInvalidStatusTransition(){Sale sale=new Sale();sale.setId(30L);sale.setStatus(SaleStatus.PAID);when(sales.findByIdForUpdate(30L)).thenReturn(Optional.of(sale));assertThrows(BusinessException.class,()->service.updateStatus(30L,new UpdateSaleStatusRequest(SaleStatus.DELIVERED)));verify(sales,never()).save(any());}
 @Test void cancellationRestoresStockOnlyOnce(){inventory.setCurrentStock(3);Sale sale=new Sale();sale.setId(30L);sale.setUser(customer);sale.setStatus(SaleStatus.PAID);SaleItem item=new SaleItem();item.setSale(sale);item.setProductVariant(variant);item.setQuantity(2);sale.getItems().add(item);when(sales.findByIdForUpdate(30L)).thenReturn(Optional.of(sale));when(inventories.findByProductVariantIdForUpdate(7L)).thenReturn(Optional.of(inventory));when(sales.save(sale)).thenReturn(sale);when(payments.findBySaleIdOrderByPaidAtAsc(30L)).thenReturn(List.of());service.updateStatus(30L,new UpdateSaleStatusRequest(SaleStatus.CANCELLED));assertEquals(5,inventory.getCurrentStock());assertThrows(BusinessException.class,()->service.updateStatus(30L,new UpdateSaleStatusRequest(SaleStatus.CANCELLED)));assertEquals(5,inventory.getCurrentStock());verify(inventories,times(1)).save(inventory);}
}
