package edu.valle.modules.store.service.impl;
import static org.junit.jupiter.api.Assertions.*; import static org.mockito.Mockito.*;
import edu.valle.modules.catalog.entity.*; import edu.valle.modules.catalog.repository.*; import edu.valle.modules.inventory.entity.Inventory; import edu.valle.modules.inventory.repository.InventoryRepository; import java.math.BigDecimal; import java.util.*; import org.junit.jupiter.api.*; import org.junit.jupiter.api.extension.ExtendWith; import org.mockito.*; import org.mockito.junit.jupiter.MockitoExtension;
@ExtendWith(MockitoExtension.class) class StoreServiceImplTest {
 @Mock ProductRepository products; @Mock ProductVariantRepository variants; @Mock InventoryRepository inventories; StoreServiceImpl service; Product product; ProductVariant active,inactive;
 @BeforeEach void setup(){service=new StoreServiceImpl(products,variants,inventories);Category c=new Category();c.setId(2L);c.setName("Camisetas");c.setActive(true);product=new Product();product.setId(1L);product.setName("Camiseta");product.setCostPrice(new BigDecimal("8"));product.setSalePrice(new BigDecimal("20"));product.setActive(true);product.setCategory(c);active=new ProductVariant();active.setId(3L);active.setSize("M");active.setColor("NEGRO");active.setSku("CAM-M-N");active.setActive(true);active.setProduct(product);inactive=new ProductVariant();inactive.setId(4L);inactive.setActive(false);inactive.setProduct(product);}
 @Test void exposesOnlyPublicProductFieldsAndActiveVariants(){when(products.findByActiveTrue()).thenReturn(List.of(product));when(variants.findByProductIdAndActiveTrue(1L)).thenReturn(List.of(active,inactive));var result=service.products(null).get(0);assertEquals(new BigDecimal("20"),result.salePrice());assertEquals(1,result.variants().size());assertFalse(Arrays.stream(result.getClass().getRecordComponents()).anyMatch(c->c.getName().equals("costPrice")));}
 @Test void variantWithoutInventoryHasZeroStock(){when(products.findByActiveTrue()).thenReturn(List.of(product));when(variants.findByProductIdAndActiveTrue(1L)).thenReturn(List.of(active));when(inventories.findByProductVariantId(3L)).thenReturn(Optional.empty());assertEquals(0,service.products(null).get(0).variants().get(0).availableStock());}
 @Test void availableInventoryStockIsExposed(){Inventory i=new Inventory();i.setCurrentStock(6);when(products.findByActiveTrue()).thenReturn(List.of(product));when(variants.findByProductIdAndActiveTrue(1L)).thenReturn(List.of(active));when(inventories.findByProductVariantId(3L)).thenReturn(Optional.of(i));assertEquals(6,service.products(null).get(0).variants().get(0).availableStock());}
 @Test void categoryFilterUsesOnlyActiveProducts(){when(products.findByActiveTrueAndCategoryId(2L)).thenReturn(List.of(product));when(variants.findByProductIdAndActiveTrue(1L)).thenReturn(List.of());assertEquals(1,service.products(2L).size());verify(products).findByActiveTrueAndCategoryId(2L);}
}
