spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/Tienda}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.secret=${JWT_SECRET:MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWYwMTIzNDU2Nzg5YWJjZGVmMDEyMzQ1Njc4OWFiY2RlZg==}

# ===============================
# SOAP SUPPLIER DATABASE
# ===============================
supplier.datasource.jdbc-url=jdbc:postgresql://localhost:5432/supplier_db
supplier.datasource.username=postgres
supplier.datasource.password=admin
supplier.datasource.driver-class-name=org.postgresql.Driver