spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/tienda_ropa}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.secret=${JWT_SECRET:MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWYwMTIzNDU2Nzg5YWJjZGVmMDEyMzQ1Njc4OWFiY2RlZg==}

supplier.datasource.jdbc-url=${SUPPLIER_DB_URL:jdbc:postgresql://localhost:5432/supplier_db}
supplier.datasource.username=${SUPPLIER_DB_USERNAME:postgres}
supplier.datasource.password=${SUPPLIER_DB_PASSWORD:admin}
supplier.datasource.driver-class-name=org.postgresql.Driver

supplier.soap.default-uri=${SUPPLIER_SOAP_URI:http://localhost:8080/ws}
