package edu.valle.modules.inventory.service.impl;
import edu.valle.common.enums.StockMovementType; import edu.valle.exception.ResourceNotFoundException; import edu.valle.modules.inventory.dto.request.*; import edu.valle.modules.inventory.dto.response.*; import edu.valle.modules.inventory.entity.*; import edu.valle.modules.inventory.mapper.InventoryMapper; import edu.valle.modules.inventory.repository.*; import edu.valle.modules.inventory.service.InventoryService; import edu.valle.modules.users.entity.User; import edu.valle.modules.users.repository.UserRepository; import java.util.List; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service @RequiredArgsConstructor public class InventoryServiceImpl implements InventoryService {
 private final InventoryRepository inventories; private final StockMovementRepository movements; private final UserRepository users; private final InventoryMapper mapper;
 @Transactional(readOnly=true) public InventoryResponse findByProductVariantId(Long id){return mapper.toResponse(find(id));}
 @Transactional public StockMovementResponse addStock(Long id,StockInRequest r){Inventory i=find(id);return mapper.toMovementResponse(change(i,user(r.userId()),StockMovementType.IN,r.quantity(),i.getCurrentStock()+r.quantity(),r.reason()));}
 @Transactional public StockMovementResponse adjustStock(Long id,StockAdjustRequest r){Inventory i=find(id);return mapper.toMovementResponse(change(i,user(r.userId()),StockMovementType.ADJUSTMENT,Math.abs(r.newStock()-i.getCurrentStock()),r.newStock(),r.reason()));}
 @Transactional(readOnly=true) public List<InventoryResponse> findLowStockProducts(){return inventories.findLowStock().stream().map(mapper::toResponse).toList();}
 private StockMovement change(Inventory i,User u,StockMovementType t,int q,int n,String reason){int previous=i.getCurrentStock();i.setCurrentStock(n);inventories.save(i);StockMovement m=new StockMovement();m.setProductVariant(i.getProductVariant());m.setUser(u);m.setMovementType(t);m.setQuantity(q);m.setPreviousStock(previous);m.setNewStock(n);m.setReason(reason);return movements.save(m);}
 private Inventory find(Long id){return inventories.findByProductVariantId(id).orElseThrow(()->new ResourceNotFoundException("Inventory not found for product variant id: "+id));}
 private User user(Long id){return users.findById(id).orElseThrow(()->new ResourceNotFoundException("User",id));}
}
