package edu.valle.modules.cart.service.impl;
import static org.junit.jupiter.api.Assertions.*; import static org.mockito.Mockito.*;
import edu.valle.common.enums.UserRole; import edu.valle.exception.*; import edu.valle.modules.cart.dto.request.CartItemRequest; import edu.valle.modules.cart.entity.*; import edu.valle.modules.cart.mapper.CartMapper; import edu.valle.modules.cart.repository.*; import edu.valle.modules.catalog.entity.*; import edu.valle.modules.catalog.repository.ProductVariantRepository; import edu.valle.modules.inventory.entity.Inventory; import edu.valle.modules.inventory.repository.InventoryRepository; import edu.valle.modules.users.entity.User; import edu.valle.modules.users.repository.UserRepository; import jakarta.validation.Validation; import java.math.BigDecimal; import java.util.*; import org.junit.jupiter.api.*; import org.junit.jupiter.api.extension.ExtendWith; import org.mockito.*; import org.mockito.junit.jupiter.MockitoExtension;
@ExtendWith(MockitoExtension.class) class CartServiceImplTest {
 @Mock CartRepository carts; @Mock CartItemRepository items; @Mock ProductVariantRepository variants; @Mock InventoryRepository inventories; @Mock UserRepository users; @Mock CartMapper mapper; CartServiceImpl service; User customer; Cart cart; ProductVariant variant; Inventory inventory;
 @BeforeEach void setup(){service=new CartServiceImpl(carts,items,variants,inventories,users,mapper);customer=new User();customer.setId(1L);customer.setUsername("ana");customer.setRole(UserRole.CUSTOMER);customer.setActive(true);cart=new Cart();cart.setId(5L);cart.setCustomer(customer);Product p=new Product();p.setId(2L);p.setSalePrice(new BigDecimal("10"));p.setActive(true);variant=new ProductVariant();variant.setId(3L);variant.setSku("SKU");variant.setActive(true);variant.setProduct(p);inventory=new Inventory();inventory.setCurrentStock(5);inventory.setProductVariant(variant);}
 private void valid(){when(variants.findById(3L)).thenReturn(Optional.of(variant));when(inventories.findByProductVariantId(3L)).thenReturn(Optional.of(inventory));}
 @Test void createsEmptyCartAutomatically(){when(carts.findByCustomerUsername("ana")).thenReturn(Optional.empty());when(users.findByUsername("ana")).thenReturn(Optional.of(customer));when(carts.save(any())).thenAnswer(i->i.getArgument(0));service.get("ana");verify(carts).save(argThat(c->c.getCustomer()==customer&&c.getItems().isEmpty()));}
 @Test void addsVariantWithoutReducingStock(){when(carts.findByCustomerUsername("ana")).thenReturn(Optional.of(cart));valid();when(items.findByCartIdAndProductVariantId(5L,3L)).thenReturn(Optional.empty());when(carts.save(cart)).thenReturn(cart);service.add("ana",new CartItemRequest(3L,2));assertEquals(1,cart.getItems().size());assertEquals(5,inventory.getCurrentStock());}
 @Test void addingExistingVariantUpdatesQuantityWithoutDuplicate(){CartItem item=new CartItem();item.setId(8L);item.setProductVariant(variant);item.setQuantity(1);cart.addItem(item);when(carts.findByCustomerUsername("ana")).thenReturn(Optional.of(cart));valid();when(items.findByCartIdAndProductVariantId(5L,3L)).thenReturn(Optional.of(item));when(carts.save(cart)).thenReturn(cart);service.add("ana",new CartItemRequest(3L,2));assertEquals(3,item.getQuantity());assertEquals(1,cart.getItems().size());}
 @Test void rejectsInsufficientStock(){when(carts.findByCustomerUsername("ana")).thenReturn(Optional.of(cart));valid();assertThrows(BusinessException.class,()->service.add("ana",new CartItemRequest(3L,6)));verify(carts,never()).save(cart);}
 @Test void rejectsInactiveVariantAndProduct(){variant.setActive(false);when(carts.findByCustomerUsername("ana")).thenReturn(Optional.of(cart));when(variants.findById(3L)).thenReturn(Optional.of(variant));assertThrows(BusinessException.class,()->service.add("ana",new CartItemRequest(3L,1)));variant.setActive(true);variant.getProduct().setActive(false);assertThrows(BusinessException.class,()->service.add("ana",new CartItemRequest(3L,1)));}
 @Test void cannotRemoveAnotherCustomersItem(){when(items.findByIdAndCartCustomerUsername(9L,"ana")).thenReturn(Optional.empty());assertThrows(ResourceNotFoundException.class,()->service.remove("ana",9L));verify(carts,never()).save(any());}
 @Test void removesItemAndClearsCart(){CartItem item=new CartItem();item.setId(8L);item.setProductVariant(variant);item.setQuantity(1);cart.addItem(item);when(items.findByIdAndCartCustomerUsername(8L,"ana")).thenReturn(Optional.of(item));when(carts.save(cart)).thenReturn(cart);service.remove("ana",8L);assertTrue(cart.getItems().isEmpty());cart.addItem(item);when(carts.findByCustomerUsername("ana")).thenReturn(Optional.of(cart));service.clear("ana");assertTrue(cart.getItems().isEmpty());}
 @Test void requestRejectsZeroAndNegativeQuantity(){try(var factory=Validation.buildDefaultValidatorFactory()){var validator=factory.getValidator();assertFalse(validator.validate(new CartItemRequest(3L,0)).isEmpty());assertFalse(validator.validate(new CartItemRequest(3L,-1)).isEmpty());}}
}
